"""initial schema

Revision ID: 9c42392dedd5
Revises:
Create Date: 2026-08-20 19:36:12.577854
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9c42392dedd5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifacts",
        sa.Column("digest", sa.String(length=71), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("digest"),
    )
    op.create_table(
        "benchmarks",
        sa.Column("key", sa.String(length=180), nullable=False),
        sa.Column("benchmark_id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("license", sa.String(length=80), nullable=False),
        sa.Column("manifest_digest", sa.String(length=71), nullable=False),
        sa.Column("manifest_json", sa.JSON(), nullable=False),
        sa.Column("manifest_path", sa.Text(), nullable=True),
        sa.Column("trusted", sa.Boolean(), nullable=False),
        sa.Column("installed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
        sa.UniqueConstraint("benchmark_id", "version", name="uq_benchmark_version"),
        sa.UniqueConstraint("manifest_digest"),
    )
    with op.batch_alter_table("benchmarks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_benchmarks_benchmark_id"), ["benchmark_id"], unique=False
        )

    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "targets",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("provider", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("capabilities_json", sa.JSON(), nullable=False),
        sa.Column("inventory_json", sa.JSON(), nullable=False),
        sa.Column("fingerprint_json", sa.JSON(), nullable=False),
        sa.Column("snapshot_digest", sa.String(length=71), nullable=False),
        sa.Column("runnable", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("targets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_targets_provider"), ["provider"], unique=False)

    op.create_table(
        "workers",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("capabilities_json", sa.JSON(), nullable=False),
        sa.Column("fingerprint_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("max_concurrency", sa.Integer(), nullable=False),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "experiments",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("project_id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("spec_json", sa.JSON(), nullable=False),
        sa.Column("spec_digest", sa.String(length=71), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("optimizer_state_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("experiments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_experiments_project_id"), ["project_id"], unique=False)

    op.create_table(
        "analysis_snapshots",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("experiment_id", sa.String(length=80), nullable=False),
        sa.Column("policy_digest", sa.String(length=71), nullable=False),
        sa.Column("input_digest", sa.String(length=71), nullable=False),
        sa.Column("code_version", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("analysis_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_analysis_experiment_created", ["experiment_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_analysis_snapshots_experiment_id"), ["experiment_id"], unique=False
        )

    op.create_table(
        "candidates",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("experiment_id", sa.String(length=80), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("parameters_json", sa.JSON(), nullable=False),
        sa.Column("config_digest", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("infeasible_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("experiment_id", "config_digest", name="uq_candidate_config"),
    )
    with op.batch_alter_table("candidates", schema=None) as batch_op:
        batch_op.create_index(
            "ix_candidate_experiment_sequence", ["experiment_id", "sequence"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_candidates_experiment_id"), ["experiment_id"], unique=False
        )

    op.create_table(
        "events",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("experiment_id", sa.String(length=80), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=False),
        sa.Column("idempotency_key", sa.String(length=180), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index("ix_event_stream", ["experiment_id", "sequence"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_events_experiment_id"), ["experiment_id"], unique=False
        )

    op.create_table(
        "evaluations",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("experiment_id", sa.String(length=80), nullable=False),
        sa.Column("candidate_id", sa.String(length=80), nullable=False),
        sa.Column("workload_id", sa.String(length=120), nullable=False),
        sa.Column("target_id", sa.String(length=100), nullable=False),
        sa.Column("target_snapshot_digest", sa.String(length=71), nullable=False),
        sa.Column("target_snapshot_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["targets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "candidate_id", "workload_id", "target_snapshot_digest", name="uq_evaluation_matrix"
        ),
    )
    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evaluations_candidate_id"), ["candidate_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_evaluations_experiment_id"), ["experiment_id"], unique=False
        )

    op.create_table(
        "attempts",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("experiment_id", sa.String(length=80), nullable=False),
        sa.Column("evaluation_id", sa.String(length=80), nullable=False),
        sa.Column("repeat_index", sa.Integer(), nullable=False),
        sa.Column("retry_index", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("fencing_token", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=100), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("envelope_json", sa.JSON(), nullable=True),
        sa.Column("envelope_digest", sa.String(length=71), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("leased_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["evaluation_id"], ["evaluations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "evaluation_id", "repeat_index", "retry_index", name="uq_attempt_repeat_retry"
        ),
        sa.UniqueConstraint("idempotency_key"),
    )
    with op.batch_alter_table("attempts", schema=None) as batch_op:
        batch_op.create_index("ix_attempt_claim", ["status", "created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_attempts_evaluation_id"), ["evaluation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_attempts_experiment_id"), ["experiment_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_attempts_worker_id"), ["worker_id"], unique=False)

    op.create_table(
        "artifact_links",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("attempt_id", sa.String(length=80), nullable=False),
        sa.Column("digest", sa.String(length=71), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.String(length=160), nullable=False),
        sa.Column("producer", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["attempt_id"], ["attempts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["digest"],
            ["artifacts.digest"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id", "digest", "role", "name", name="uq_artifact_link"),
    )
    with op.batch_alter_table("artifact_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_artifact_links_attempt_id"), ["attempt_id"], unique=False
        )

    op.create_table(
        "checks",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("attempt_id", sa.String(length=80), nullable=False),
        sa.Column("check_id", sa.String(length=120), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("scope", sa.String(length=24), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["attempt_id"], ["attempts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("checks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_checks_attempt_id"), ["attempt_id"], unique=False)

    op.create_table(
        "observations",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("attempt_id", sa.String(length=80), nullable=False),
        sa.Column("metric", sa.String(length=120), nullable=False),
        sa.Column("value_number", sa.Float(), nullable=True),
        sa.Column("value_boolean", sa.Boolean(), nullable=True),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("phase", sa.String(length=24), nullable=False),
        sa.Column("workload", sa.String(length=120), nullable=True),
        sa.Column("sample_index", sa.Integer(), nullable=True),
        sa.Column("sample_count", sa.Integer(), nullable=True),
        sa.Column("statistic", sa.String(length=24), nullable=False),
        sa.Column("timestamp_text", sa.String(length=48), nullable=True),
        sa.Column("attributes_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["attempt_id"], ["attempts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "attempt_id", "metric", "phase", "sample_index", "statistic", name="uq_observation"
        ),
    )
    with op.batch_alter_table("observations", schema=None) as batch_op:
        batch_op.create_index("ix_observation_metric", ["attempt_id", "metric"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_observations_attempt_id"), ["attempt_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("observations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_observations_attempt_id"))
        batch_op.drop_index("ix_observation_metric")

    op.drop_table("observations")
    with op.batch_alter_table("checks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_checks_attempt_id"))

    op.drop_table("checks")
    with op.batch_alter_table("artifact_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artifact_links_attempt_id"))

    op.drop_table("artifact_links")
    with op.batch_alter_table("attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attempts_worker_id"))
        batch_op.drop_index(batch_op.f("ix_attempts_experiment_id"))
        batch_op.drop_index(batch_op.f("ix_attempts_evaluation_id"))
        batch_op.drop_index("ix_attempt_claim")

    op.drop_table("attempts")
    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evaluations_experiment_id"))
        batch_op.drop_index(batch_op.f("ix_evaluations_candidate_id"))

    op.drop_table("evaluations")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_experiment_id"))
        batch_op.drop_index("ix_event_stream")

    op.drop_table("events")
    with op.batch_alter_table("candidates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidates_experiment_id"))
        batch_op.drop_index("ix_candidate_experiment_sequence")

    op.drop_table("candidates")
    with op.batch_alter_table("analysis_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analysis_snapshots_experiment_id"))
        batch_op.drop_index("ix_analysis_experiment_created")

    op.drop_table("analysis_snapshots")
    with op.batch_alter_table("experiments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_experiments_project_id"))

    op.drop_table("experiments")
    op.drop_table("workers")
    with op.batch_alter_table("targets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_targets_provider"))

    op.drop_table("targets")
    op.drop_table("projects")
    with op.batch_alter_table("benchmarks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_benchmarks_benchmark_id"))

    op.drop_table("benchmarks")
    op.drop_table("artifacts")
    # ### end Alembic commands ###
