import { useMutation, useQuery } from '@tanstack/react-query';
import { AlertTriangle, Boxes, Cpu, Download, ExternalLink, Filter, Plus, RefreshCw, Search, Server } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ImportTargetDialog } from '../components/ImportTargetDialog';
import { PageHeader } from '../components/PageHeader';
import { EmptyState, ErrorState, LoadingState } from '../components/States';
import { TargetStatus } from '../components/StatusBadge';
import { TargetSshButton } from '../components/TargetSshButton';
import { api } from '../lib/api';
import { formatDate } from '../lib/format';

export function BenchmarksPage() {
  const [search,setSearch]=useState(''); const query=useQuery({queryKey:['benchmarks'],queryFn:api.benchmarks});
  const items=useMemo(()=>query.data?.items.filter(x=>!search||`${x.name} ${x.description||''} ${x.category||''} ${(x.tags||[]).join(' ')}`.toLowerCase().includes(search.toLowerCase()))||[],[query.data,search]);
  return <div className="page"><PageHeader title="场景目录" description="注册 Benchmark，查看采购问题、workload 拓扑和证据状态。" actions={<Link className="button primary" to="/benchmarks/register"><Plus size={16}/>注册 Benchmark</Link>}/><div className="notice warning catalog-compatibility-note"><AlertTriangle size={18}/><div><strong>兼容阶段：注册不等于准入</strong><p>服务端注册记录显示“已登记未准入”；历史合同缺少注册证据时显示“历史未审计”。两者都不会被推断为已通过正式选型审计。</p></div></div><div className="toolbar"><label className="search-field"><Search size={16}/><span className="sr-only">搜索场景</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索名称、分类或标签"/></label><span className="result-count">{items.length} 个场景</span></div>{query.isLoading?<LoadingState/>:query.isError?<ErrorState error={query.error} onRetry={()=>query.refetch()}/>:items.length?<div className="catalog-grid">{items.map(x=><article className="catalog-item" key={x.id}><div className="catalog-icon"><Boxes size={20}/></div><div className="catalog-main"><div className="catalog-title"><h2>{x.name}</h2>{x.version&&<span className="tag">{x.version}</span>}<span className="benchmark-audit-state">{x.auditStatus==='registered-not-admitted'?'已登记未准入':'历史未审计'}</span></div><p>{x.decisionQuestion||x.description||'暂无场景说明。'}</p><div className="catalog-meta"><span>{x.category==='scenario'?'选型场景':x.category==='unclassified'?'未分类':x.category||'未分类'}</span><span>执行模型：{x.executionModel||'custom'}</span><span>{x.runnable?'可执行':'不可执行合同'}</span><span>{x.cases==null?'workload 未知':`${x.cases} 个 workload`}</span><span>更新 {formatDate(x.updatedAt)}</span></div>{x.metrics?.length&&<div className="tags">{x.metrics.map(v=><span key={v}>{v}</span>)}</div>}</div></article>)}</div>:<EmptyState title="没有匹配的场景"/>}</div>;
}

export function TargetsPage() {
  const [search,setSearch]=useState(''); const [status,setStatus]=useState('active'); const [importOpen,setImportOpen]=useState(false); const query=useQuery({queryKey:['targets','all'],queryFn:()=>api.targets(true),refetchInterval:30_000});
  const sync=useMutation({mutationFn:()=>api.syncTencentTargets(),onSuccess:()=>query.refetch()});
  const items=useMemo(()=>query.data?.items.filter(x=>{const statusMatches=status==='all'||(status==='active'?x.lifecycleStatus!=='missing'&&x.lifecycleStatus!=='archived':status==='missing'||status==='archived'?x.lifecycleStatus===status:x.status===status);return statusMatches&&(!search||`${x.name} ${x.id} ${x.framework||''} ${x.hardware||''}`.toLowerCase().includes(search.toLowerCase()));})||[],[query.data,search,status]);
  const lifecycleLabel=(target:typeof items[number])=>target.lifecycleStatus==='archived'?'历史归档':target.lifecycleStatus==='missing'?`云端不可见 · 连续 ${target.inventoryMissCount||1} 次`:'当前活跃';
  return <div className="page"><PageHeader title="候选资源" description="查看服务器规格、环境指纹和执行就绪状态。" actions={<><button className="button secondary" disabled={sync.isPending} onClick={()=>sync.mutate()}><RefreshCw size={15}/>{sync.isPending?'同步中…':'同步腾讯云库存'}</button><button className="button primary" onClick={()=>setImportOpen(true)}><Download size={15}/>连接外部机器</button></>}/>{sync.isError&&<div className="inline-alert"><AlertTriangle size={16}/>{sync.error.message}</div>}<div className="toolbar"><label className="search-field"><Search size={16}/><span className="sr-only">搜索目标</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索名称、框架或硬件"/></label><label className="select-field"><Filter size={15}/><select aria-label="资源状态" value={status} onChange={e=>setStatus(e.target.value)}><option value="active">活跃资源</option><option value="missing">云端不可见</option><option value="archived">历史归档</option><option value="online">Worker 在线</option><option value="inventory">仅库存</option><option value="degraded">异常</option><option value="offline">离线</option><option value="all">全部状态</option></select></label><span className="result-count">{items.length} 个资源</span></div>{query.isLoading?<LoadingState/>:query.isError?<ErrorState error={query.error} onRetry={()=>query.refetch()}/>:items.length?<section className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>资源</th><th>执行状态</th><th>资源生命周期</th><th>运行时</th><th>硬件</th><th>最后确认</th><th>端点</th><th>SSH 连接</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><div className="resource-name"><span className="resource-icon"><Server size={16}/></span><div><strong>{x.name}</strong><span className="cell-meta">{x.type||x.id}</span></div></div></td><td><TargetStatus status={x.status}/></td><td>{lifecycleLabel(x)}{x.missingSince&&<span className="cell-meta">缺失始于 {formatDate(x.missingSince)}</span>}</td><td>{x.framework||'—'}<span className="cell-meta">{x.version||''}</span></td><td><span className="inline-icon"><Cpu size={14}/>{x.hardware||'—'}</span></td><td>{formatDate(x.lastInventorySeenAt||x.lastSeenAt)}</td><td>{x.endpoint?.startsWith('http')?<a className="text-link" href={x.endpoint} target="_blank" rel="noreferrer">打开<ExternalLink size={14}/></a>:x.endpoint?<code>{x.endpoint}</code>:'—'}</td><td><TargetSshButton target={x}/></td></tr>)}</tbody></table></div></section>:<EmptyState title="没有匹配的候选资源" description={status==='active'?'同步云库存后，云端不可见的资源会移入历史筛选。':undefined}/>}<ImportTargetDialog open={importOpen} onClose={()=>setImportOpen(false)}/></div>;
}
